pdxruby/pdxruby.github.io

.gitmodules
README.md
index.md

Github pages will automatically pull in submodules,see
https://help.github.com/articles/using-submodules-with-pages/

Include /old as a git submodule.

---

links.jsonp

used by prose.io to help select local links

fix broken layout for links.jsonp

---

404.html
_layouts/default.html
js/edit.js

Add github as an option to edit and create pages

---

_config.yml

Prose polish

---

history.md

Added some links to a few references

Update history with link to my page

---

past-meetings.md

Adds the videos from July 2016's meetup to the past meetings page.
/cc @edrex 
:heart:

Add July 2016 videos

---

past-meetings.md

Add August 2016 videos

---

past-meetings.md

Add September/October 2016 vids

---

contributions.md

This new format makes more sense and is much more clear.
Thanks for the review, mom! :wink:

Reformat contributions for they are clearer

---

past-meetings.md

Add November meetup video

---

past-meetings.md

Add Jan/March meetup videos

---

past-meetings.md

I'm a bit behind! Links to April, May and August meetups :heart:

Add some videos

---

contributions.md

Add Rico's contribution

---

past-meetings.md

It looks like I added links to some of the videos from the creator
studio (which will take you to the /edit page) instead of the public
/watch page. Oops!

Fix youtube links

---

past-meetings.md

Add links for Sept 2018 videos.

Add video links for Sept 2018 meetup

---

past-meetings.md

Adds links for Oct. videos. Thanks!

Add links for October videos

---

past-meetings.md

Added links for June videos that just got posted over the weekend.
Thanks!

Add links for June videos

---

past-meetings.md

Add links for November 2018 videos.

Add links for November videos

---

past-meetings.md

Add links for Feb 2019 videos

---

suggested-presentations.md

- Updates the list of suggested presentations.  List gleaned from the February 2019 Ruby Tuesday meetup.

Update Suggested Presentations for 2019

---

past-meetings.md

Adds links for April 2019 videos.

Add links for April 2019 videos

---

past-meetings.md

Add links for May 2019 videos

---

past-meetings.md

Add links for June video

---

past-meetings.md

Add links for October 2019 videos

---

past-meetings.md

Add links for January 2020 videos

---

past-meetings.md

Adds links to February 2020 videos.

Add links for February videos

---

past-meetings.md

Adds the links. Did not make a video for Jonan's short talk as it was basically a very abridged version of the same talk he's given the past 2 months.

Add link for march video/playlist
